c_e472 = [
    {
        "raw_dn": b"o=c_e472,c=it",
        "dn": "o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=AvvStudioA,o=c_e472,c=it",
        "dn": "ou=AvvStudioA,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=SegrSindaco,o=c_e472,c=it",
        "dn": "ou=SegrSindaco,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Ced-SviluppoInformatico,ou=SegrSindaco,o=c_e472,c=it",
        "dn": "ou=Ced-SviluppoInformatico,ou=SegrSindaco,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser7200,o=c_e472,c=it",
        "dn": "ou=ser7200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=DirittoStudio,ou=ser7200,o=c_e472,c=it",
        "dn": "ou=DirittoStudio,ou=ser7200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=SegreteriaGen,o=c_e472,c=it",
        "dn": "ou=SegreteriaGen,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser4100,o=c_e472,c=it",
        "dn": "ou=ser4100,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser4200,o=c_e472,c=it",
        "dn": "ou=ser4200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser4300,o=c_e472,c=it",
        "dn": "ou=ser4300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser5100,o=c_e472,c=it",
        "dn": "ou=ser5100,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser5200,o=c_e472,c=it",
        "dn": "ou=ser5200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser5300,o=c_e472,c=it",
        "dn": "ou=ser5300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser6100,o=c_e472,c=it",
        "dn": "ou=ser6100,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser6200,o=c_e472,c=it",
        "dn": "ou=ser6200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser7300,o=c_e472,c=it",
        "dn": "ou=ser7300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser8100,o=c_e472,c=it",
        "dn": "ou=ser8100,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser8200,o=c_e472,c=it",
        "dn": "ou=ser8200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ser8300,o=c_e472,c=it",
        "dn": "ou=ser8300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=SerAffGen,o=c_e472,c=it",
        "dn": "ou=SerAffGen,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ServAffariIstit,o=c_e472,c=it",
        "dn": "ou=ServAffariIstit,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ServDemDec,o=c_e472,c=it",
        "dn": "ou=ServDemDec,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ServGareContratt,o=c_e472,c=it",
        "dn": "ou=ServGareContratt,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ServGrandiOpere,o=c_e472,c=it",
        "dn": "ou=ServGrandiOpere,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ServManutenzioni,o=c_e472,c=it",
        "dn": "ou=ServManutenzioni,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ServPolizMunicip,o=c_e472,c=it",
        "dn": "ou=ServPolizMunicip,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=ServRisUmane,o=c_e472,c=it",
        "dn": "ou=ServRisUmane,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff-Elettorale,ou=ServDemDec,o=c_e472,c=it",
        "dn": "ou=Uff-Elettorale,ou=ServDemDec,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff-Turismo,ou=ser8300,o=c_e472,c=it",
        "dn": "ou=Uff-Turismo,ou=ser8300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=UffAsiliNido,ou=ser7200,o=c_e472,c=it",
        "dn": "ou=UffAsiliNido,ou=ser7200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=UffFarmacie,ou=ser7200,o=c_e472,c=it",
        "dn": "ou=UffFarmacie,ou=ser7200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Ufficio_Transizione_Digitale,o=c_e472,c=it",
        "dn": "ou=Ufficio_Transizione_Digitale,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=UffProgettiUE,o=c_e472,c=it",
        "dn": "ou=UffProgettiUE,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=UffProtCiv,o=c_e472,c=it",
        "dn": "ou=UffProtCiv,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=UffViabilita,ou=ser6200,o=c_e472,c=it",
        "dn": "ou=UffViabilita,ou=ser6200,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff_DistrPiano,ou=ser7300,o=c_e472,c=it",
        "dn": "ou=Uff_DistrPiano,ou=ser7300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff_Economato,ou=SerAffGen,o=c_e472,c=it",
        "dn": "ou=Uff_Economato,ou=SerAffGen,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff_eFatturaPA,o=c_e472,c=it",
        "dn": "ou=Uff_eFatturaPA,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff_Energia,ou=ServManutenzioni,o=c_e472,c=it",
        "dn": "ou=Uff_Energia,ou=ServManutenzioni,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff_InclSociale,ou=ser7300,o=c_e472,c=it",
        "dn": "ou=Uff_InclSociale,ou=ser7300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
    {
        "raw_dn": b"ou=Uff_SerSocAss,ou=ser7300,o=c_e472,c=it",
        "dn": "ou=Uff_SerSocAss,ou=ser7300,o=c_e472,c=it",
        "raw_attributes": {},
        "attributes": {},
        "type": "searchResEntry",
    },
]
c_e472_full = {
    "raw_dn": b"o=c_e472,c=it",
    "dn": "o=c_e472,c=it",
    "raw_attributes": {
        "objectClass": [b"top", b"organization", b"amministrazione"],
        "o": [b"c_e472"],
        "tipoAmm": [b"L6"],
        "description": [b"Comune di Latina"],
        "postalCode": [b"04100"],
        "l": [b"Latina"],
        "provincia": [b"LT"],
        "regione": [b"Lazio"],
        "nomeResp": [b"Damiano"],
        "cognomeResp": [b"Coletta"],
        "titoloResp": [b"Sindaco"],
        "sitoIstituzionale": [b"www.comune.latina.it"],
        "st": [b"ACCREDITATA"],
        "dataVerifica": [b"2018-09-18"],
        "codiceFiscaleAmm": [b"00097020598"],
        "codiceAmm": [b"125155432201"],
        "street": [b"Piazza del Popolo, 1"],
        "macroTipoAmm": [b"PA"],
        "mail": [b"protocollo@pec.comune.latina.it"],
        "contatti": [
            b"segreteria.generale@pec.comune.latina.it#pec",
            b"servizio.attivitaproduttive@pec.comune.latina.it#pec",
            b"urp@pec.comune.latina.it#pec",
            b"scuolaculturasport@pec.comune.latina.it#pec",
        ],
        "nomeS": [
            b"1#Albo Pretorio",
            b"2#Gare e Appalti",
            b"3#Moduli on-line",
            b"4#Trasparenza Amministrativa",
            b"5#Ufficio TIA",
            b"6#Residenze in tempo reale",
            b"7#Ufficio di Stato Civile",
        ],
        "descrizioneS": [
            b"1#Albo Pretorio",
            b"2#Gare e Appalti on line",
            b"3#Moduli on-line",
            b"4#Trasparenza Amministrativa",
            b"5#Ufficio TIA",
            b"6#Residenze in tempo reale",
            b"7#Ufficio di Stato Civile",
        ],
        "fruibS": [
            b"1#true",
            b"2#true",
            b"3#true",
            b"4#true",
            b"5#true",
            b"6#true",
            b"7#true",
        ],
        "mailS": [
            b"1#accessocivico@pec.comune.latina.it",
            b"2#servizio.gare@pec.comune.latina.it",
            b"3#urp@pec.comune.latina.it",
            b"4#accessocivico@pec.comune.latina.it",
            b"5#ufficio.tia@pec.comune.latina.it",
            b"6#iscrizionianagrafiche@comune.latina.it",
            b"7#statocivile@pec.comune.latina.it",
        ],
        "servizioTelematico": [
            b"1#http://trasparenza.comune.latina.it/web/trasparenza/albo-pretorio",
            b"2#http://www.comune.latina.it/c-638/gare-e-appalti-on-line",
            b"3#http://www.comune.latina.it/c-496/moduli-on-line",
            b"4#http://trasparenza.comune.latina.it",
            b"5#http://www.comune.latina.it/c-380/gestione-tia",
            b"6#http://www.comune.latina.it/a-8494/abitare/residenze-in-tempo-reale",
            b"7#http://www.comune.latina.it/c-138/stato-civile",
        ],
        "mailSPub": [b"1#s", b"2#s", b"3#s", b"4#s", b"5#s", b"6#s", b"7#s"],
        "telephonenumberS": [b"7#0773652511"],
    },
    "attributes": {
        "objectClass": ["top", "organization", "amministrazione"],
        "o": ["c_e472"],
        "tipoAmm": "L6",
        "description": ["Comune di Latina"],
        "postalCode": ["04100"],
        "l": ["Latina"],
        "provincia": "LT",
        "regione": "Lazio",
        "nomeResp": "Damiano",
        "cognomeResp": "Coletta",
        "titoloResp": "Sindaco",
        "sitoIstituzionale": "www.comune.latina.it",
        "st": ["ACCREDITATA"],
        "dataVerifica": "2018-09-18",
        "codiceFiscaleAmm": "00097020598",
        "codiceAmm": "125155432201",
        "street": ["Piazza del Popolo, 1"],
        "macroTipoAmm": "PA",
        "mail": ["protocollo@pec.comune.latina.it"],
        "contatti": [
            "segreteria.generale@pec.comune.latina.it#pec",
            "servizio.attivitaproduttive@pec.comune.latina.it#pec",
            "urp@pec.comune.latina.it#pec",
            "scuolaculturasport@pec.comune.latina.it#pec",
        ],
        "nomeS": [
            "1#Albo Pretorio",
            "2#Gare e Appalti",
            "3#Moduli on-line",
            "4#Trasparenza Amministrativa",
            "5#Ufficio TIA",
            "6#Residenze in tempo reale",
            "7#Ufficio di Stato Civile",
        ],
        "descrizioneS": [
            "1#Albo Pretorio",
            "2#Gare e Appalti on line",
            "3#Moduli on-line",
            "4#Trasparenza Amministrativa",
            "5#Ufficio TIA",
            "6#Residenze in tempo reale",
            "7#Ufficio di Stato Civile",
        ],
        "fruibS": [
            "1#true",
            "2#true",
            "3#true",
            "4#true",
            "5#true",
            "6#true",
            "7#true",
        ],
        "mailS": [
            "1#accessocivico@pec.comune.latina.it",
            "2#servizio.gare@pec.comune.latina.it",
            "3#urp@pec.comune.latina.it",
            "4#accessocivico@pec.comune.latina.it",
            "5#ufficio.tia@pec.comune.latina.it",
            "6#iscrizionianagrafiche@comune.latina.it",
            "7#statocivile@pec.comune.latina.it",
        ],
        "servizioTelematico": [
            "1#http://trasparenza.comune.latina.it/web/trasparenza/albo-pretorio",
            "2#http://www.comune.latina.it/c-638/gare-e-appalti-on-line",
            "3#http://www.comune.latina.it/c-496/moduli-on-line",
            "4#http://trasparenza.comune.latina.it",
            "5#http://www.comune.latina.it/c-380/gestione-tia",
            "6#http://www.comune.latina.it/a-8494/abitare/residenze-in-tempo-reale",
            "7#http://www.comune.latina.it/c-138/stato-civile",
        ],
        "mailSPub": ["1#s", "2#s", "3#s", "4#s", "5#s", "6#s", "7#s"],
        "telephonenumberS": ["7#0773652511"],
    },
    "type": "searchResEntry",
}

c_e472 = {
    "objectClass": ["top", "organization", "amministrazione"],
    "o": ["c_e472"],
    "tipoAmm": "L6",
    "description": ["Comune di Latina"],
    "postalCode": ["04100"],
    "l": ["Latina"],
    "provincia": "LT",
    "regione": "Lazio",
    "nomeResp": "Damiano",
    "cognomeResp": "Coletta",
    "titoloResp": "Sindaco",
    "sitoIstituzionale": "www.comune.latina.it",
    "st": ["ACCREDITATA"],
    "dataVerifica": "2018-09-18",
    "codiceFiscaleAmm": "00097020598",
    "codiceAmm": "125155432201",
    "street": ["Piazza del Popolo, 1"],
    "macroTipoAmm": "PA",
    "mail": ["protocollo@pec.comune.latina.it"],
    "contatti": [
        "segreteria.generale@pec.comune.latina.it#pec",
        "servizio.attivitaproduttive@pec.comune.latina.it#pec",
        "urp@pec.comune.latina.it#pec",
        "scuolaculturasport@pec.comune.latina.it#pec",
    ],
    "nomeS": [
        "1#Albo Pretorio",
        "2#Gare e Appalti",
        "3#Moduli on-line",
        "4#Trasparenza Amministrativa",
        "5#Ufficio TIA",
        "6#Residenze in tempo reale",
        "7#Ufficio di Stato Civile",
    ],
    "descrizioneS": [
        "1#Albo Pretorio",
        "2#Gare e Appalti on line",
        "3#Moduli on-line",
        "4#Trasparenza Amministrativa",
        "5#Ufficio TIA",
        "6#Residenze in tempo reale",
        "7#Ufficio di Stato Civile",
    ],
    "fruibS": ["1#true", "2#true", "3#true", "4#true", "5#true", "6#true", "7#true"],
    "mailS": [
        "1#accessocivico@pec.comune.latina.it",
        "2#servizio.gare@pec.comune.latina.it",
        "3#urp@pec.comune.latina.it",
        "4#accessocivico@pec.comune.latina.it",
        "5#ufficio.tia@pec.comune.latina.it",
        "6#iscrizionianagrafiche@comune.latina.it",
        "7#statocivile@pec.comune.latina.it",
    ],
    "servizioTelematico": [
        "1#http://trasparenza.comune.latina.it/web/trasparenza/albo-pretorio",
        "2#http://www.comune.latina.it/c-638/gare-e-appalti-on-line",
        "3#http://www.comune.latina.it/c-496/moduli-on-line",
        "4#http://trasparenza.comune.latina.it",
        "5#http://www.comune.latina.it/c-380/gestione-tia",
        "6#http://www.comune.latina.it/a-8494/abitare/residenze-in-tempo-reale",
        "7#http://www.comune.latina.it/c-138/stato-civile",
    ],
    "mailSPub": ["1#s", "2#s", "3#s", "4#s", "5#s", "6#s", "7#s"],
    "telephonenumberS": ["7#0773652511"],
}

umc_latina_m_inf = {
    "objectClass": ["top", "organization", "organizationalUnit", "ufficio"],
    "description": ["Motorizzazione Civile Latina"],
    "ou": ["Umc-Latina"],
    "o": ["m_inf"],
    "street": ["Strada Congiunte Destre"],
    "postalCode": ["04100"],
    "l": ["Latina"],
    "provincia": "LT",
    "regione": "Lazio",
    "CodiceUnivocoUO": "98W3U5",
    "aooRef": "aoo=DGTC,o=m_inf,c=it",
    "mail": ["umc-latina@pec.mit.gov.it"],
    "dataVerifica": "2014-06-06",
    "nomeResp": "Dirigente non",
    "cognomeResp": "previsto",
    "telephonenumberRespSFE": "077346631",
    "MailRespSFE": "umc-latina@pec.mit.gov.it",
    # valorizzato solo se c'è il servizio di
    # fatturazione
    "codiceUO": "98W3U5",
    "canaleTrasmissivoSFE": "SPCOOP",
    "nomeSFE": "FATTURAZIONE",
    "intermediarioSFE": "si",
    "URISFE": "https://MinisteroEconomiaFinanze.spcoop.gov.it/openspcoop/PA/MEF/DFP_SIFE_RicezioneFatture_1",
    "codiceFiscaleSFE": "80007830591",
    "dataVerificaCFSFE": "2014-04-10",
    "dataAvvioSFE": "2014-06-06",
}
uc_trento = {
    "objectClass": ["top", "organization", "amministrazione"],
    "o": ["aasnq"],
    "tipoAmm": "L7",
    "description": ["Azienda Sanitaria Universitaria Integrata di Udine"],
    "postalCode": ["33100"],
    "l": ["Udine"],
    "provincia": "UD",
    "regione": "Friuli Venezia Giulia",
    "nomeResp": "Mauro",
    "cognomeResp": "Delendi",
    "titoloResp": "Direttore Generale",
    "sitoIstituzionale": "www.asuiud.sanita.fvg.it",
    "st": ["ACCREDITATA"],
    "Acronimo": "ASUIUD",
    "dataVerifica": "2016-05-19",
    "codiceFiscaleAmm": "02801610300",
    "street": ["Via Pozzuolo 330"],
    "macroTipoAmm": "PA",
    "mail": ["asuiud@certsanita.fvg.it"],
    "nomeS": [
        "1#Pagamenti online",
        "2#Situazione pazienti nei Pronto Soccorso",
        "3#Albo pretorio telematico",
        "4#Consultazione tempi d'attesa",
        "5#Prenotazione online",
        "6#Referti Online",
    ],
    "descrizioneS": [
        "1#Pagamenti online",
        "2#Situazione pazienti nei Pronto Soccorso",
        "3#Albo pretorio telematico",
        "4#Consultazione tempi d'attesa visite ed esami",
        "5#Prenotazione online visite ed esami",
        "6#Referti online",
    ],
    "fruibS": ["1#true", "2#true", "3#true", "4#true", "5#true", "6#true"],
    "servizioTelematico": [
        "1#https://pagamentionline.regione.fvg.it/PagamentoVolontarioSanita/Login.jsp",
        "2#servizionline.sanita.fvg.it/psonline/",
        "3#http://albopretorio.regione.fvg.it/AAS4",
        "4#https://servizionline.sanita.fvg.it/prenotazioni/#/index",
        "5#https://servizionline.sanita.fvg.it/prenotazioni/#/index",
        "6#https://refertionline.sanita.fvg.it/SERVIZIFVG_RefertiOnLine/cercaRichiesta",
    ],
    "mailSPub": ["1#n", "2#n", "3#n", "4#n", "5#n", "6#s"],
    "mailS": ["6#ds@asuiud.sanita.fvg.it"],
}

AvvStudioA_c_e472 = {
    "objectClass": ["top", "organization", "organizationalUnit", "ufficio"],
    "description": ["Avvocatura Studio A"],
    "ou": ["AvvStudioA"],
    "o": ["c_e472"],
    "street": ["Via Duca del Mare"],
    "postalCode": ["04100"],
    "l": ["Latina"],
    "provincia": "LT",
    "regione": "Lazio",
    "nomeResp": "Francesco",
    "cognomeResp": "Di Leginio",
    "mailResp": "avvocatura@comune.latina.it",
    "CodiceUnivocoUO": "KF05EG",
    "mail": ["servizio.avvocatura@pec.comune.latina.it"],
    "dataVerifica": "2015-03-31",
    "codiceUO": "KF05EG",
    "nomeSFE": "FATTURAZIONE",
    "canaleTrasmissivoSFE": "PEC",
    "telephonenumberRespSFE": "0773652358",
    "MailRespSFE": "avvocatura@comune.latina.it",
    "intermediarioSFE": "no",
    "mailSFE": "Uff_eFatturaPA@pec.comune.latina.it",
    "URISFE": "null",
    "mailSFEPEC": "pec",
    "codiceFiscaleSFE": "00097020598",
    "dataVerificaCFSFE": "2015-03-17",
    "dataAvvioSFE": "2015-03-31",
}

ced_c_e472 = {
    "objectClass": ["top", "organization", "organizationalUnit", "ufficio"],
    "description": ["Ced - Sviluppo Informatico"],
    "ou": ["Ced-SviluppoInformatico"],
    "o": ["c_e472"],
    "street": ["Piazza del Popolo 1"],
    "postalCode": ["04100"],
    "l": ["Latina"],
    "provincia": "LT",
    "regione": "Lazio",
    "nomeResp": "Luciano",
    "cognomeResp": "Cisi",
    "telephonenumberResp": "0773652377",
    "telephoneNumber": ["0773652377"],
    "mailResp": "luciano.cisi@comune.latina.it",
    "CodiceUnivocoUO": "2MPZQ8",
    "mail": ["ced@pec.comune.latina.it"],
    "contatti": ["applicazioni.software@pec.comune.latina.it#pec"],
    "dataVerifica": "2015-03-31",
    "codiceUO": "2MPZQ8",
    "nomeSFE": "FATTURAZIONE",
    "canaleTrasmissivoSFE": "PEC",
    "telephonenumberRespSFE": "0773652377",
    "MailRespSFE": "luciano.cisi@omune.latina.it",
    "intermediarioSFE": "si",
    "mailSFE": "Uff_eFatturaPA@pec.comune.latina.it",
    "mailSFEPEC": "pec",
    "codiceFiscaleSFE": "00097020598",
    "dataVerificaCFSFE": "2016-01-14",
    "dataAvvioSFE": "2015-03-31",
}
